### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by Michael-F-Bryan** [hotg-ai/librunecoral#5]
We'll need to implement versioning so that updating one of our main dependencies (i.e. TensorFlow Lite or `libedgetpu`) will cause a semver-compatible change in `librunecoral`'s version number.

**Comment by Michael-F-Bryan** [comment]
We've asked about TensorFlow Lite and `libedgetpu`'s compatibility guarantees upstream. See https://github.com/google-coral/libedgetpu/issues/26.

**Comment by saidinesh5** [comment]
We don't need to expose any more API functions to expose library versions as the preferred way of linking is static linking.

for eg.
v0.3.0 => will always come with tensroflow 2.6 and corresponding version of libedgetpu tested to work with it
When we update tensorflow version to 2.7, we can update librunecoral version to v0.4.0.

So closing this issue.
